#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
        [[ ! -f /tmp/auto-whu.log ]] && touch /tmp/auto-whu.log
        procd_open_instance
        procd_set_param command /usr/sbin/auto-whu.sh
        procd_set_param respawn
        procd_close_instance
}